# Generated by Django 2.2.2 on 2019-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
            },
        ),
    ]
